openapi: 3.1.0
info:
  title: Oracle
  description: public api for oracle application
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /prophecy:
    get: 
      description: retrive prophetic quote
      responses: 
        200:
          description: 'ok'
          content: 
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                    description: prophetic quote
                  used: 
                    type: boolean
                    description: used or not  
    post: 
      description: post own predictive quote   
      requestBody: 
        required: true
        content: 
          application/json:
            schema:
              type: object
              properties: 
                content:
                  type: string
                  required: true
                used: 
                  type: boolean
                  required: false
      responses: 
        200:
          description: 'ok'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  content:
                    type: string
                    description: prophetic quote
                  used:
                    type: boolean
                    description: used or not
            
                  
                  
  